CFLAGS=-std=c++11

all:stack-vm

stack-vm: stack-vm.o main.o
	$(CXX) $(CFLAGS) -o stack-vm stack-vm.o main.o
	
main.o:main.cpp
	$(CXX) $(CFLAGS) -c main.cpp

stack-vm.o: stack-vm.h stack_vm.cpp
	$(CXX) $(CFLAGS) -c stack_vm.cpp

clean:
	rm -f *.o

